env: !!python/object:loaders_v2.configloader.ConfigLoader
  env:
    device: cuda
    p_config: /media/scratch1/jonfrey/datasets/config/
    p_ycb: /media/scratch1/jonfrey/datasets/YCB_Video_Dataset
    p_ycb_config: /home/jonfrey/datasets/config
    p_ycb_dense_test: datasets/ycb/dataset_config/test_data_list.txt
    p_ycb_dense_train: datasets/ycb/dataset_config/train_data_list.txt
    p_ycb_lookup_desig_to_obj: /home/jonfrey/datasets/config/desig_obj_list.npy
    p_ycb_obj: datasets/ycb/dataset_config/classes.txt
    p_ycb_seq_test: datasets/ycb/dataset_config/test_data_list_seq.txt
    p_ycb_seq_train: datasets/ycb/dataset_config/train_data_list_seq.txt
    p_ycb_seq_train_inc_syn: datasets/ycb/dataset_config/train_data_list_seq_inc_syn.txt
    p_ycb_syn: datasets/ycb/dataset_config/data_syn.txt
exp: !!python/object:loaders_v2.configloader.ConfigLoader
  env:
    backbone: DenseFusion
    criterion: std
    d_test:
      batch_list_cfg:
        add_syn_to_train: true
        fixed_length: true
        mode: dense_fusion_test
        seq_length: 1
        sequence_names: null
        sub_sample: 1
      name: ycb
      noise_cfg:
        noise_trans: 0.01
        status: true
      num_points: 1000
      num_pt_mesh_large: 2300
      num_pt_mesh_small: 500
      obj_list_fil: null
      obj_list_sym:
      - 12
      - 15
      - 18
      - 19
      - 20
      objects: 21
      output_cfg:
        add_depth_image: false
        ff:
          noise_degree: 2
          noise_m: 0.01
          prediction: ground_truth
          status: true
          time_lag_frames: 5
        force_one_object_visible: true
        refine: false
        status: false
        visu:
          return_img: true
          status: true
    d_train:
      batch_list_cfg:
        add_syn_to_train: true
        fixed_length: true
        mode: dense_fusion_train
        seq_length: 1
        sequence_names: null
        sub_sample: 1
      name: ycb
      noise_cfg:
        noise_trans: 0.01
        status: true
      num_points: 1000
      num_pt_mesh_large: 2300
      num_pt_mesh_small: 500
      obj_list_fil: null
      obj_list_sym:
      - 12
      - 15
      - 18
      - 19
      - 20
      objects: 21
      output_cfg:
        add_depth_image: false
        ff:
          noise_degree: 2
          noise_m: 0.01
          prediction: ground_truth
          status: true
          time_lag_frames: 5
        force_one_object_visible: true
        refine: false
        status: false
        visu:
          return_img: true
          status: true
    decay_margin_start: 0.016
    epochs: 500
    loader:
      batch_size: 1
      shuffle: true
      workers: 16
    log_epoch: 1
    log_seq: 100
    lr_normal: 0.0001
    lr_normal_rate: 0.3
    mail: false
    model_load: /home/jonfrey/results/runs/YCB_tomato_soup/00:00_reduced_complexity_final
    model_mode: train
    model_path: /home/jonfrey/results/runs/lightning/2020-06-22T13:12:58_debug
    model_restore: false
    optimizer: ADAM
    samples_early_break_epoch: 5000000
    samples_early_break_validation: 100000
    save_epoch: 1
    tensorboard: true
    tensorboard_path: /home/jonfrey/results/tensorboard/YCB_tomato_soup/debug
    test_epoch: 1
    time_early_break_epoch: 10
    time_early_break_validation: 10
    train_batch: 8
    visu: true
    visu_cfg:
      break_iter: 1
      epoch: 1
      refine_start: false
      same_cad_model: true
    w_normal: 0.015
    w_normal_rate: 0.3
