model_path: "/home/jonfrey/results/runs/lightning/debug"
estimator_restore: true
estimator_load: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_model_26_0.012863246640872631.pth"
refiner_restore: false
refiner_load: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_refine_model_69_0.009449292959118935.pth"

mail: false

accumulate_grad_batches: 8

epochs: 500
lr: 0.0001
lr_cfg:
  on_plateau_cfg:
    mode: "min"
    factor: 0.3
    threshold: 0.02
  interval: "epoch"
  frequency: 1

early_stopping_cfg:
  patience: 4

w_normal: 0.015
w_normal_rate: 0.3

decay_margin_start: 0.016
samples_early_break_epoch: 5000000
time_early_break_epoch: 10
samples_early_break_validation: 100000
time_early_break_validation: 10

loader:
  batch_size: 1
  workers: 4

d_test:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 500
  num_pt_mesh_large: 2300
  obj_list_fil: null # if not null add list with specific elements
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 3
    fixed_length: true
    sub_sample: 1
    mode: "test" #dense_fusion_test
    add_syn_to_train: false
  noise_cfg:
    status: false
    noise_trans: 0.0
  output_cfg:
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: false
    visu:
      status: true
      return_img: true

d_train:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 500
  num_pt_mesh_large: 2300
  obj_list_fil: null # if not null add list with specific elements
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 3
    fixed_length: true
    sub_sample: 1
    mode: "train"
    add_syn_to_train: true
  noise_cfg:
    status: true
    noise_trans: 0.01
  output_cfg:
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: false
    visu:
      status: true
      return_img: true
